spring:
  application:
    name: oauth2-server

#  # Database
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa

  # JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
    generate-ddl: true
    properties:
      format_sql: true
    show-sql: true
  data:
    redis:
      password: gosl111
      port: 6379

#logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

server:
  port: 8100